DROP TABLE TB_BOARD;
DROP TABLE TB_USER;
DROP TABLE TB_TEST;

CREATE TABLE TB_USER (
    USER_ID VARCHAR2(100),
    USER_NM VARCHAR2(100),
    USER_PW VARCHAR2(100),
    CONSTRAINT TB_USER_PK PRIMARY KEY (USER_ID)
);

INSERT INTO TB_USER VALUES ('test', '홍길동', '1') ;

CREATE TABLE TB_BOARD (
    NO NUMBER,
    TITLE VARCHAR2(100),
    MEMO CLOB,
    USER_ID VARCHAR2(100),
    REGDATE DATE,
    CONSTRAINT TB_BOARD_PK PRIMARY KEY (NO),
    CONSTRAINT TB_BOARD_USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES TB_USER(USER_ID) ON DELETE CASCADE
);

CREATE TABLE TB_TEST (
    DATA1 NUMBER,
    DATA2 VARCHAR2(100)
);