DROP TABLE IF EXISTS TB_USER;

CREATE TABLE TB_USER (
	ID INT,
	PW VARCHAR2(100) NOT NULL,
	NAME VARCHAR2(50) NOT NULL,
	ADDR VARCHAR2(4000),
	REGDATE DATE,
	MODDATE TIMESTAMP,
	ETC CLOB,
	CONSTRAINT TB_USER_ID_PK PRIMARY KEY (ID)
);

INSERT INTO TB_USER (ID, PW, NAME, ADDR, REGDATE, MODDATE, ETC) VALUES (1, 'ghdrlfehd', '홍길동', '서울', '2011-10-13', '2011-10-13 12:31:59', '비고');